# Generated by Django 2.2.28 on 2022-04-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Event_code', models.IntegerField()),
                ('Event_name', models.CharField(max_length=25)),
                ('Event_location', models.CharField(max_length=15)),
                ('Event_Org', models.CharField(max_length=15)),
                ('Event_start_date', models.DateTimeField()),
                ('Event_end_date', models.DateTimeField()),
                ('Event_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Users',
            fields=[
                ('User_id', models.IntegerField(primary_key=True, serialize=False)),
                ('User_Fname', models.CharField(max_length=15)),
                ('User_Lname', models.CharField(max_length=15)),
                ('Username', models.CharField(max_length=15)),
                ('Social_id', models.CharField(max_length=15)),
                ('Bio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Socials',
            fields=[
                ('Social_id', models.IntegerField(primary_key=True, serialize=False)),
                ('twitter', models.CharField(max_length=15)),
                ('instagram', models.CharField(max_length=15)),
                ('snapchat', models.CharField(max_length=15)),
                ('cashapp', models.CharField(max_length=15)),
                ('Event_host', models.BooleanField(default=False)),
                ('Event_performer', models.BooleanField(default=False)),
                ('Event_guest', models.CharField(max_length=15)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event_Users')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_id', models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('User_id', models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='event.Event_Users')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='Event_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event_Users'),
        ),
    ]
