# Generated by Django 2.2.27 on 2022-04-21 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20220421_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_attendee',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='event_attendee',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='event_host',
            name='host_id',
        ),
        migrations.RemoveField(
            model_name='event_socials',
            name='host_id',
        ),
        migrations.RemoveField(
            model_name='event_socials',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Event_Attendee',
        ),
        migrations.DeleteModel(
            name='Event_Host',
        ),
        migrations.DeleteModel(
            name='Event_Socials',
        ),
        migrations.DeleteModel(
            name='Event_Users',
        ),
    ]
