# Generated by Django 2.2.27 on 2022-04-21 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_auto_20220421_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_code', models.IntegerField()),
                ('event_name', models.CharField(max_length=55, null=True)),
                ('event_location', models.CharField(max_length=30, null=True)),
                ('event_org', models.CharField(max_length=30, null=True)),
                ('event_start_date', models.DateTimeField()),
                ('event_end_date', models.DateTimeField()),
                ('event_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_fname', models.CharField(max_length=30, null=True)),
                ('host_lname', models.CharField(max_length=30, null=True)),
                ('host_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_fname', models.CharField(max_length=30, null=True)),
                ('user_lname', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Socials',
            fields=[
                ('social_id', models.IntegerField(primary_key=True, serialize=False)),
                ('twitter', models.CharField(max_length=30, null=True)),
                ('instagram', models.CharField(max_length=30, null=True)),
                ('snapchat', models.CharField(max_length=30, null=True)),
                ('Facebook', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('user_bio', models.TextField(max_length=255, null=True)),
                ('event_host', models.BooleanField(default=False)),
                ('event_performer', models.BooleanField(default=False)),
                ('event_guest', models.BooleanField(default=False)),
                ('host_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event_Host')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event_Users')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('user_id', models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to='event.Event_Users')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event_Users'),
        ),
    ]
