# Generated by Django 2.2.27 on 2022-04-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20220427_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_code_short',
            field=models.CharField(default='VGHfqHJ', max_length=10),
        ),
    ]
