# Generated by Django 2.2.27 on 2022-05-10 03:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_event_code_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.UUIDField(default=uuid.UUID('bf2f0b34-1690-41de-9b3c-b0bdcf850cb4'), editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code_short',
            field=models.CharField(default='c2tnb6A', max_length=10),
        ),
        migrations.AlterField(
            model_name='event_socials',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
