# Generated by Django 2.2.27 on 2022-04-21 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20220421_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_host',
            name='host_fname',
        ),
        migrations.RemoveField(
            model_name='event_host',
            name='host_id',
        ),
        migrations.RemoveField(
            model_name='event_host',
            name='host_lname',
        ),
    ]
