# Generated by Django 2.2.28 on 2022-05-04 01:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_event_code_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.UUIDField(default=uuid.UUID('31148967-3d0b-4edb-a321-f3a3323caf02'), editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code_short',
            field=models.CharField(default='Ajkbs2F', max_length=10),
        ),
    ]
