# Generated by Django 2.2.27 on 2022-04-21 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20220421_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_socials',
            name='host_id',
        ),
    ]
