# Generated by Django 2.2.28 on 2022-05-05 01:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20220504_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.UUIDField(default=uuid.UUID('10a27d30-dcd9-4102-bdff-c1cc40a32c49'), editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code_short',
            field=models.CharField(default='4xhxuCQ', max_length=10),
        ),
    ]
