# Generated by Django 2.2.27 on 2022-04-21 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_event_socials_host_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_socials',
            old_name='event_guest',
            new_name='is_event_guest',
        ),
        migrations.RenameField(
            model_name='event_socials',
            old_name='event_host',
            new_name='is_event_host',
        ),
        migrations.RenameField(
            model_name='event_socials',
            old_name='event_performer',
            new_name='is_event_performer',
        ),
        migrations.AddField(
            model_name='event_host',
            name='host_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event_Users'),
        ),
        migrations.AddField(
            model_name='event_host',
            name='social_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event_Socials'),
        ),
    ]
