# Generated by Django 2.2.28 on 2022-05-05 03:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20220505_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.UUIDField(default=uuid.UUID('ff5d955e-554d-4b66-a329-dc8e9857a605'), editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code_short',
            field=models.CharField(default='oSo6VK4', max_length=10),
        ),
    ]
