# Generated by Django 2.2.28 on 2022-05-10 02:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20220505_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.UUIDField(default=uuid.UUID('55125546-4317-415f-a8fb-20da8123fd99'), editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code_short',
            field=models.CharField(default='H9kz7xh', max_length=10),
        ),
    ]
