# Generated by Django 2.2.28 on 2022-05-10 03:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20220510_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.UUIDField(default=uuid.UUID('f224b606-c180-4634-bfc3-70f6641bedbb'), editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code_short',
            field=models.CharField(default='m6hojTF', max_length=10),
        ),
        migrations.AlterField(
            model_name='event_socials',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
