# Generated by Django 2.2.27 on 2022-05-10 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20220510_0320'),
        ('event', '0005_auto_20220510_0320'),
    ]

    operations = [
    ]
