# Generated by Django 2.2.27 on 2022-05-11 02:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_merge_20220510_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.UUIDField(default=uuid.UUID('0e543c2c-bcd9-499e-9c85-8b9a4b5480a4'), editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code_short',
            field=models.CharField(default='4ZL9MRx', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event_attendee',
            name='event_id',
            field=models.ForeignKey(editable=False, max_length=12, on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
        migrations.AlterField(
            model_name='event_host',
            name='host',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event_Users'),
        ),
        migrations.AlterField(
            model_name='event_socials',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event_socials',
            name='social_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event_users',
            name='user_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
