# Generated by Django 2.2.27 on 2022-05-13 03:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20220511_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='about_event',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.UUIDField(default=uuid.UUID('12128317-adee-4581-8f43-00f0cb02f92c'), editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code_short',
            field=models.CharField(default='5EHz9BQ', max_length=10),
        ),
    ]
