# Generated by Django 2.2.27 on 2022-05-15 03:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20220513_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='auth_user',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.UUIDField(default=uuid.UUID('9d3dc18f-e631-49c3-81b1-15a9c0fbfce0'), editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code_short',
            field=models.CharField(default='VyfmpxZ', max_length=10),
        ),
    ]
