# Generated by Django 2.2.27 on 2022-05-15 03:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20220515_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_host',
            name='auth_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.UUIDField(default=uuid.UUID('7d9c29ee-ccf2-4beb-9314-32e9eccc118e'), editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code_short',
            field=models.CharField(default='QMsrAL6', max_length=10),
        ),
    ]
